/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AttendeesIndexRouteImport } from './routes/attendees/index'
import { Route as EventsNewRouteImport } from './routes/events/new'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as EEventIdRouteImport } from './routes/e/$eventId'
import { Route as CheckinEventIdRouteImport } from './routes/checkin/$eventId'
import { Route as AttendeesNewRouteImport } from './routes/attendees/new'
import { Route as EventsEventIdEditRouteImport } from './routes/events/$eventId_.edit'
import { Route as AttendeesUserIdEditRouteImport } from './routes/attendees/$userId_.edit'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesIndexRoute = AttendeesIndexRouteImport.update({
  id: '/attendees/',
  path: '/attendees/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EEventIdRoute = EEventIdRouteImport.update({
  id: '/e/$eventId',
  path: '/e/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinEventIdRoute = CheckinEventIdRouteImport.update({
  id: '/checkin/$eventId',
  path: '/checkin/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesNewRoute = AttendeesNewRouteImport.update({
  id: '/attendees/new',
  path: '/attendees/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/events/$eventId_/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesUserIdEditRoute = AttendeesUserIdEditRouteImport.update({
  id: '/attendees/$userId_/edit',
  path: '/attendees/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/profile': typeof ProfileRoute
  '/upgrade': typeof UpgradeRoute
  '/attendees/new': typeof AttendeesNewRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/e/$eventId': typeof EEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/attendees/': typeof AttendeesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/attendees/$userId/edit': typeof AttendeesUserIdEditRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/profile': typeof ProfileRoute
  '/upgrade': typeof UpgradeRoute
  '/attendees/new': typeof AttendeesNewRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/e/$eventId': typeof EEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/attendees': typeof AttendeesIndexRoute
  '/events': typeof EventsIndexRoute
  '/attendees/$userId/edit': typeof AttendeesUserIdEditRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/profile': typeof ProfileRoute
  '/upgrade': typeof UpgradeRoute
  '/attendees/new': typeof AttendeesNewRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/e/$eventId': typeof EEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/attendees/': typeof AttendeesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/attendees/$userId_/edit': typeof AttendeesUserIdEditRoute
  '/events/$eventId_/edit': typeof EventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/login'
    | '/organizations'
    | '/profile'
    | '/upgrade'
    | '/attendees/new'
    | '/checkin/$eventId'
    | '/e/$eventId'
    | '/events/$eventId'
    | '/events/new'
    | '/attendees/'
    | '/events/'
    | '/attendees/$userId/edit'
    | '/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/login'
    | '/organizations'
    | '/profile'
    | '/upgrade'
    | '/attendees/new'
    | '/checkin/$eventId'
    | '/e/$eventId'
    | '/events/$eventId'
    | '/events/new'
    | '/attendees'
    | '/events'
    | '/attendees/$userId/edit'
    | '/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/organizations'
    | '/profile'
    | '/upgrade'
    | '/attendees/new'
    | '/checkin/$eventId'
    | '/e/$eventId'
    | '/events/$eventId'
    | '/events/new'
    | '/attendees/'
    | '/events/'
    | '/attendees/$userId_/edit'
    | '/events/$eventId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  ProfileRoute: typeof ProfileRoute
  UpgradeRoute: typeof UpgradeRoute
  AttendeesNewRoute: typeof AttendeesNewRoute
  CheckinEventIdRoute: typeof CheckinEventIdRoute
  EEventIdRoute: typeof EEventIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsNewRoute: typeof EventsNewRoute
  AttendeesIndexRoute: typeof AttendeesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  AttendeesUserIdEditRoute: typeof AttendeesUserIdEditRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees/': {
      id: '/attendees/'
      path: '/attendees'
      fullPath: '/attendees/'
      preLoaderRoute: typeof AttendeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$eventId': {
      id: '/e/$eventId'
      path: '/e/$eventId'
      fullPath: '/e/$eventId'
      preLoaderRoute: typeof EEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$eventId': {
      id: '/checkin/$eventId'
      path: '/checkin/$eventId'
      fullPath: '/checkin/$eventId'
      preLoaderRoute: typeof CheckinEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees/new': {
      id: '/attendees/new'
      path: '/attendees/new'
      fullPath: '/attendees/new'
      preLoaderRoute: typeof AttendeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId_/edit': {
      id: '/events/$eventId_/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees/$userId_/edit': {
      id: '/attendees/$userId_/edit'
      path: '/attendees/$userId/edit'
      fullPath: '/attendees/$userId/edit'
      preLoaderRoute: typeof AttendeesUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  ProfileRoute: ProfileRoute,
  UpgradeRoute: UpgradeRoute,
  AttendeesNewRoute: AttendeesNewRoute,
  CheckinEventIdRoute: CheckinEventIdRoute,
  EEventIdRoute: EEventIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsNewRoute: EventsNewRoute,
  AttendeesIndexRoute: AttendeesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  AttendeesUserIdEditRoute: AttendeesUserIdEditRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
